dbt_exam:
  outputs:
    dev:
      account: DWPVANY-FI58115
      database: DB_DST_EXAM
      password: P8zkE4aKxkNsq7H
      role: ACCOUNTADMIN
      schema: STAR_SCHEMA
      threads: 1
      type: snowflake
      user: BRM01
      warehouse: WAREHOUSE_DST
  target: dev
